# Generated by Django 3.2 on 2022-08-10 02:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20220809_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookitem',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('95376f8c-191a-45b1-8cd4-dd9b57c3d2ec')),
        ),
    ]
