# Generated by Django 3.2 on 2022-07-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cell_phone',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
    ]
