# Generated by Django 3.2 on 2022-08-10 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_auto_20220809_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hallway', models.IntegerField()),
                ('category', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='RackBookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('book_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bookitem')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.rack')),
            ],
        ),
    ]
